# dev config - keep this in version control for ease
spring:
  datasource:
    url: jdbc:postgresql://localhost:5001/maval
    username: postgres
    password: test
  jpa:
    hibernate:
      # allow spring to create db tables
      ddl-auto: create